# DO NOT EDIT THIS FILE! This file gets overwritten for each update.
# Use the files below to set global server settings and variables.
if(file.exists("/etc/opencpu/Renviron")) readRenviron("/etc/opencpu/Renviron")
if(file.exists("/etc/opencpu/Rprofile")) source("/etc/opencpu/Rprofile")

# Load the 'unix' package
ocpu_syslib <- '/usr/lib/opencpu/library'
.libPaths(ocpu_syslib)

#Load suggested packages while they are in .libPaths()
getNamespace("unix")
getNamespace("sendmailR")

# Add the 'opencpu' (requires unix from the syslib)
tryCatch({
  ocpu_homelib <- gsub("^~", unix::user_info('opencpu')$dir, Sys.getenv("R_LIBS_USER"))
  .libPaths(c(ocpu_syslib, ocpu_homelib))
  rm(ocpu_homelib)
}, error = function(e){
  cat("No 'opencpu' system user")
})
rm(ocpu_syslib)

#Default locale in apache is "C"
if(grepl("UTF-?8", Sys.getlocale("LC_CTYPE"))){
  cat("Current locale is:", Sys.getlocale("LC_CTYPE"), "\n")
} else {
  Sys.setlocale(category = "LC_ALL", "en_US.UTF-8")
  cat("Setting locale to en_US.UTF-8\n")
}

#Set environment variables
Sys.setenv(LANG = Sys.getlocale("LC_CTYPE"))

#Try to disable interactivity
#try(.Call(parallel:::C_mc_interactive, FALSE))
sys:::set_interactive(FALSE)

#We use this later
options(rapache = TRUE)

#Check if AppArmor is available
tryCatch({
  getNamespace("RAppArmor")
  if(RAppArmor::aa_is_enabled() && identical("unconfined", try(RAppArmor::aa_getcon()$con))){
    options(apparmor = TRUE)
    cat("AppArmor available! Running OpenCPU with security profile and rlimits.\n")
  } else {
    cat("AppArmor not available. Running OpenCPU without security profile but with rlimits.\n")
  }
}, error = function(e){
  options(no_rapparmor = TRUE)
  cat("RAppArmor not installed. Running OpenCPU without security profile or rlimits.\n")
})

#Warm up graphics device
options(bitmapType = "cairo")
svg("/dev/null", width = 11.69, height = 8.27)
plot(1:10)
dev.off()

#Warm up RNG, JSON
invisible(openssl::rand_bytes(1000))
invisible(jsonlite::toJSON(iris))
