#!/bin/bash
set -e

# Setup postfix if not done yet
if [ -f "/mailgun.txt" ] && [ ! -f "/etc/postfix/setupok" ]; then
  echo "Configuring postfix..."
  touch "/etc/postfix/setupok"
  sed -i '/^relayhost/d' /etc/postfix/main.cf
  cat /mailgun.txt >> /etc/postfix/main.cf
fi

# Start background services
service postfix start
service cron start 
/usr/lib/rstudio-server/bin/rserver

# Start OpenCPU in foreground (blocking)
apachectl -DFOREGROUND
