#! /bin/sh

set -e

case "$1" in
  remove | abort-install)
    :
      rm -f /etc/ssl/certs/ocpu.pem
      rm -f /etc/ssl/certs/opencpu.pem
      rm -f /etc/init.d/opencpu-cache
      update-rc.d -f opencpu-cache remove
    ;;
  purge | disappear | upgrade | failed-upgrade | abort-upgrade)
    :
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 1;;
esac

#DEBHELPER#

exit 0
