#!/bin/sh
### BEGIN INIT INFO
# Provides:          opencpu-cache
# Required-Start:    $local_fs $remote_fs $network $syslog $named nginx
# Required-Stop:     $local_fs $remote_fs $network $syslog $named nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop OpenCPU Caching Service.
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
  	#just in case nginx isnt started yet
	service nginx start 2>&1 >/dev/null | grep -i  'error' || true

    iptables -A INPUT -p tcp --dport 80 -j ACCEPT
    iptables -A INPUT -p tcp --dport 443 -j ACCEPT
    iptables -A INPUT -p tcp --dport 8006 -j ACCEPT
    iptables -A INPUT -p tcp --dport 8007 -j ACCEPT
    iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 8006 
    iptables -A PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 8007  
    iptables -A OUTPUT -t nat -o lo -p tcp --dport 80 -j REDIRECT --to-ports 8006
    iptables -A OUTPUT -t nat -o lo -p tcp --dport 443 -j REDIRECT --to-ports 8007 

	/usr/lib/opencpu/scripts/nginx_ensite opencpu 2>&1 >/dev/null | grep -i  'error' || true
	service nginx reload || true
	
	echo "OK"
	;;
  stop)
    echo "Disabling caching server..."

    /usr/lib/opencpu/scripts/nginx_dissite opencpu 2>&1 >/dev/null | grep -i  'error' || true
    service nginx restart || true
    
    echo "Flushing cache..."
    rm -Rf /tmp/opencpu-cache
    
    echo "Cleaning up iptables..."
	iptables -D INPUT -p tcp --dport 80 -j ACCEPT
	iptables -D INPUT -p tcp --dport 443 -j ACCEPT
	iptables -D INPUT -p tcp --dport 8006 -j ACCEPT
	iptables -D INPUT -p tcp --dport 8007 -j ACCEPT
	iptables -D PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 8006 
	iptables -D PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 8007  
	iptables -D OUTPUT -t nat -o lo -p tcp --dport 80 -j REDIRECT --to-ports 8006
	iptables -D OUTPUT -t nat -o lo -p tcp --dport 443 -j REDIRECT --to-ports 8007    
    
    echo "OK"  
    ;;
  restart | force-reload)
	$0 stop
	$0 start
	;;
  wipe)
    iptables -F
    iptables -X
    iptables -t nat -F
    iptables -t nat -X
    iptables -t mangle -F
    iptables -t mangle -X
    iptables -P INPUT ACCEPT
    iptables -P FORWARD ACCEPT
    iptables -P OUTPUT ACCEPT
    ;;      
  *)
    echo "Usage: service opencpu-cache {start|stop|restart}"
    exit 1
    ;;
esac