name: Build base image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse tag from ref
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build opencpu/base
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: docker/base
          push: true
          tags: |
            opencpu/base:latest
            opencpu/base:${{ steps.vars.outputs.tag }}
            ghcr.io/${{github.repository}}/base:latest

      - name: Build opencpu/rstudio
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64 #rstudio does not support arm64
          context: docker/rstudio
          push: true
          tags: |
            opencpu/rstudio:latest
            opencpu/rstudio:${{ steps.vars.outputs.tag }}
            ghcr.io/${{github.repository}}/rstudio:latest

      - name: Build opencpu/apps
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: docker/apps
          push: true
          tags: |
            opencpu/apps:latest
            opencpu/apps:${{ steps.vars.outputs.tag }}
            ghcr.io/${{github.repository}}/apps:latest
