name: Build distro images

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ 'centos-7', 'centos-8', 'debian-11', 'fedora-34', 'ubuntu-18.04', 'ubuntu-20.04', 'rocky-8' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse tag from ref
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker/${{ matrix.os }}
          build-args: |
            BRANCH=${{ steps.vars.outputs.tag }}
            RSTUDIO=1.4.1717
          push: true
          tags: |
            opencpu/${{matrix.os}}:latest
            opencpu/${{matrix.os}}:${{ steps.vars.outputs.tag }}
            ghcr.io/${{github.repository}}/${{matrix.os}}:latest
