on:
  workflow_dispatch:

name: Submit to launchpad

jobs:
  Build:
    runs-on: ubuntu-24.04
    name: 'Sign and upload to Launchpad'

    steps:
      - name: Prepare system
        run: |
          sudo apt-get update
          sudo add-apt-repository -y "ppa:marutter/rrutter4.0"
          sudo apt-get install -y git gnupg curl devscripts equivs gdebi-core
          mkdir -p ~/.gnupg
          echo "default-cache-ttl 46000" >> ~/.gnupg/gpg-agent.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
          curl -sSL $GPG_KEY > private.pgp
          gpg --batch --yes --import private.pgp
          rm -f private.pgp
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo mk-build-deps -i

      - name: Build and sign source package
        run: |
          export GPG_TTY=$(tty)
          echo "DEBUILD_TGZ_CHECK=no" >> ~/.devscripts
          debuild -S -i -I -p"gpg --batch --yes --passphrase $GPG_PASS --pinentry-mode loopback"
          sed -i.bak 's|noble|jammy|g' debian/changelog
          debuild -S -i -I -p"gpg --batch --yes --passphrase $GPG_PASS --pinentry-mode loopback"
        env:
          GPG_PASS: ${{ secrets.GPG_PASS }}

      - name: Upload to launchpad
        run: |
          cd ..
          dput ppa:opencpu/opencpu-2.2 *.changes
